m1721: Remove deprecated configstore HAL from device manifest
android.hardware.configstore@1.1::ISurfaceFlingerConfigs has been
removed from the Android 14 framework compatibility matrix, causing
VINTF compatibility check to fail with:

  ERROR: The following instances are in the device manifest but not
  specified in framework compatibility matrix:
    android.hardware.configstore@1.1::ISurfaceFlingerConfigs/default